[phases.setup]
nixPkgs = ['php83', 'php83Extensions.pdo', 'php83Extensions.pdo_mysql', 'php83Extensions.mbstring', 'php83Extensions.xml', 'php83Extensions.curl', 'php83Extensions.zip', 'php83Extensions.gd', 'nodejs_20']

[phases.build]
cmds = [
    'cd src && composer install --no-dev --optimize-autoloader',
    'cd src && npm install',
    'cd src && npm run build'
]

[start]
cmd = 'cd src && php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT'
